//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENAC_IT_BUDGET.Models.ENACIT_Budget
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class enacit_budget : DbContext
    {
        public enacit_budget()
            : base("name=enacit_budget")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_commande> tb_commande { get; set; }
        public virtual DbSet<tb_commandeinventaire> tb_commandeinventaire { get; set; }
        public virtual DbSet<tb_commandepaiement> tb_commandepaiement { get; set; }
        public virtual DbSet<tb_commandreception> tb_commandreception { get; set; }
        public virtual DbSet<tb_commandStatus> tb_commandStatus { get; set; }
        public virtual DbSet<tb_contact_role> tb_contact_role { get; set; }
        public virtual DbSet<tb_espace> tb_espace { get; set; }
        public virtual DbSet<tb_fonctionunit> tb_fonctionunit { get; set; }
        public virtual DbSet<tb_fournisseur> tb_fournisseur { get; set; }
        public virtual DbSet<tb_unit> tb_unit { get; set; }
        public virtual DbSet<tb_unit_contact> tb_unit_contact { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_octroisunit> tb_octroisunit { get; set; }
        public virtual DbSet<tb_send_message> tb_send_message { get; set; }
    }
}
