//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENAC_IT_BUDGET.Models.ENACIT_Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_commande()
        {
            this.tb_commandeinventaire = new HashSet<tb_commandeinventaire>();
        }
    
        public string NoCommande { get; set; }
        public short NoUnit { get; set; }
        public System.DateTime DateCommande { get; set; }
        public string PersonneCommande { get; set; }
        public short NoFournisseur { get; set; }
        public string DescriptionObjet { get; set; }
        public decimal Montant { get; set; }
        public short ToInventorier { get; set; }
        public string Remarques { get; set; }
        public short CommandeYear { get; set; }
        public string CommandeRef { get; set; }
        public string CouleurRemarques { get; set; }
    
        public virtual tb_fournisseur tb_fournisseur { get; set; }
        public virtual tb_unit tb_unit { get; set; }
        public virtual tb_user tb_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_commandeinventaire> tb_commandeinventaire { get; set; }
        public virtual tb_commandepaiement tb_commandepaiement { get; set; }
        public virtual tb_commandreception tb_commandreception { get; set; }
        public virtual tb_commandStatus tb_commandStatus { get; set; }
    }
}
