//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENAC_IT_BUDGET.Models.ENACIT_Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fournisseur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fournisseur()
        {
            this.tb_commande = new HashSet<tb_commande>();
        }
    
        public short NoFournisseur { get; set; }
        public string NomFournisseur { get; set; }
        public string Remarques { get; set; }
        public short IsValid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_commande> tb_commande { get; set; }
    }
}
