//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENAC_IT_BUDGET.Models.ENACIT_Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_fonctionunit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_fonctionunit()
        {
            this.tb_user = new HashSet<tb_user>();
        }
    
        public short NoFonction { get; set; }
        public string NomFonction { get; set; }
        public string GroupName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_user> tb_user { get; set; }
    }
}
