//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENAC_IT_BUDGET.Models.ENACIT_Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_octroisunit
    {
        public short OctroisYear { get; set; }
        public short NoUnit { get; set; }
        public decimal OctroisBase { get; set; }
        public decimal OctroisCorrige { get; set; }
        public string Remarques { get; set; }
        public short isClosed { get; set; }
    
        public virtual tb_unit tb_unit { get; set; }
    }
}
