//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENAC_IT_BUDGET.Models.ENACIT_Budget
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_send_message
    {
        public long ID { get; set; }
        public short NoUnit { get; set; }
        public string EmailAdresse { get; set; }
        public short EmailType { get; set; }
        public System.DateTime SendTime { get; set; }
        public short SendStatus { get; set; }
        public string MessageObjet { get; set; }
        public string MessageBody { get; set; }
        public string ErrorMessage { get; set; }
    }
}
